version: '3.3'

services:
  db:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes: 
      - my-db: /var/lib/mysql
    
  app:
    container_name: java-con
    build: .
    links:
      - db
    

volumes:
  my-db:
  
  





