version: '3.7'

services:
  api:
    build: .
    container_name: java-app
    links: 
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql
    

    

volumes:
  mydb:

  
  





