version: '3.3'

services:
  db:
    image: 'mysql:latest'
    restart:always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "27017:27017"
    volumes: 
      - mongodb: /data/db
    
  app:
    container_name: java-con
    ports:
      - "4000:4000"
    build:
      context: ./
      dockerfile: ./services/api/app/Dockerfile
    links:
      - db
  
  





``
