version: '3.3'

services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes: 
      - my-db: /var/lib/mysql
    
  app:
    build: .
    links:
      - db
    

volumes:
  my-db:
  
  





